<a href="https://colab.research.google.com/github/Thiago-Reis-Porto/treinamento-h2ia/blob/main/Relat%C3%B3rio_Busca_com_heuristica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# O Problema
Sliding Puzzle - Bloco Deslizante

In [ ]:
# !wget -qq https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif
from IPython.display import Image
Image(url='https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif',width=200)


# Resolver o quebra-cabeças usando Buscas

In [ ]:
import numpy as np

solution = np.array([[1,2,3],[4,5,6],[7,8,0]])

#---------------------------------------------------------------------------------------------------------
#--Classe do quebra-cabeça--------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------

class Puzzle:
  
  #Construtor recebe o pai e o estado(ou gera um estado aleatorio)
  def __init__(self, parent, state = np.random.choice([i for i in range(9)] , size=(3, 3), replace=False)):
    self.state = state #array com o estado
    self.blankPos = list(map(lambda x: x[0],(np.where(self.state == 0))) ) #posição do espaço
    self.isSolution = np.array_equal(solution,self.state) 
    self.parent = parent
    self.g = self.__G_Cost()#self.__blank_Cost()
    self.h = self.__H_Cost()
    self.f = self.g + self.h
    self.visited = False
    self.children = [] #proximos movimentos possiveis
    

#---------------------------------------------------------------------------------------------------------
#-Movimentos - -------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------
  #Move espaço para esquerda se possivel
  def __moveL(self):
    blankPos = self.blankPos
    if blankPos[1] == 0:
      return np.array([])
    newState = self.state.copy()
    newState[blankPos[0]][blankPos[1]] = newState[blankPos[0]][blankPos[1]-1]
    newState[blankPos[0]][blankPos[1]-1] = 0
    return newState
  
  #Move espaço para direita se possivel
  def __moveR(self):
    blankPos = self.blankPos
    if blankPos[1] == 2:
      return np.array([])
    newState = self.state.copy()    
    newState[blankPos[0]][blankPos[1]] = newState[blankPos[0]][blankPos[1]+1]
    newState[blankPos[0]][blankPos[1]+1] = 0
    return newState
  
  #Move espaço para cima se possivel
  def __moveU(self):
    blankPos = self.blankPos
    if blankPos[0] == 0:
      return np.array([])
    newState = self.state.copy()
    newState[blankPos[0]][blankPos[1]] = newState[blankPos[0]-1][blankPos[1]]
    newState[blankPos[0]-1][blankPos[1]] = 0
    return newState
  #Move espaço para baixo se possivel
  def __moveD(self):
    blankPos = self.blankPos
    if blankPos[0] == 2:
      return np.array([])
    newState = self.state.copy()
    newState[blankPos[0]][blankPos[1]] = newState[blankPos[0]+1][blankPos[1]]
    newState[blankPos[0]+1][blankPos[1]] = 0
    return newState

#---------------------------------------------------------------------------------------------------------
#-----------Gera os proximos movimentos possiveis a partir do estado atual--------------------------------
#---------------------------------------------------------------------------------------------------------
  def genChildren(self):
    moves = [self.__moveR, self.__moveL, self.__moveU, self.__moveD]
    for i in moves:
      newMove = i()
      if newMove.any() and self.parent == None:
        self.children.append(Puzzle(self, newMove))
      
      elif newMove.any() and not np.array_equal(newMove, self.parent.state): 
        self.children.append(Puzzle(self, newMove))
#---------------------------------------------------------------------------------------------------------
#-------------------------------Metodos para heuristicas--------------------------------------------------
#---------------------------------------------------------------------------------------------------------
  def __H_Cost(self):
    cost = 0;
    for i in range(3):
      for j in range(3):
        if i==j==2:
          return cost
        if self.state[i][j] != solution[i][j]:
          cost+=1
  def __G_Cost(self):
    if not self.parent:
      return 0
    else:
      return self.parent.g + 1
  
  def updateF(self):
    self.f = self.g + self.h

  def updateG(self, g):
    self.g = g
  
#-----test
  def __blank_Cost(self):  
      return 2 - self.blankPos[0] + 2 - self.blankPos[1]


## Busca A*

In [ ]:
 
def aStar(puzzle):
  def isIn(state, nodes):
    for i in nodes:
      if np.array_equal(state, i.state):
        return i
    return None
  
  nodes_explored = 0
  if puzzle.isSolution:
    print("Nós expandidos = 0")
    return puzzle
  
  frontier = { 'open':[], 'closed':[]}
  frontier['open'].append(puzzle)
  
  while True:
    
    puzzle.genChildren()
    
    frontier['open'].remove(puzzle)
    frontier['closed'].append(puzzle)
  
    for i in puzzle.children:
      aux = isIn(i.state, frontier['open'])
      if aux:
        if aux.g > i.g:
          aux.updateG(i.g)
          aux.updateF()          
      elif not isIn(i.state, frontier['closed']):
        frontier['open'].append(i)
    
    puzzle = frontier['open'][0]
    for i in frontier['open']:
      if puzzle.f > i.f:
        puzzle = i

    #[ x for x in frontier['open'] if not (x==i).all()]
    nodes_explored+=1
    if puzzle.isSolution:
      print("Nós expandidos =", nodes_explored)
      return puzzle
    


In [20]:
p = Puzzle(None,np.array([[1, 5, 2], [3, 8,6], [7, 0, 4]]))
print(p.state)
s = aStar(p)


[[1 5 2]
 [3 8 6]
 [7 0 4]]
Nós expandidos = 423


In [ ]:
#-----printa solução------------
pr=s;
while (pr.parent):
  print(str(pr.state))
  print("\n")
  pr=pr.parent
print(pr.state)


[[1 2 3]
 [4 5 6]
 [7 8 0]]


[[1 2 3]
 [4 5 0]
 [7 8 6]]


[[1 2 3]
 [4 0 5]
 [7 8 6]]


[[1 2 3]
 [0 4 5]
 [7 8 6]]


[[0 2 3]
 [1 4 5]
 [7 8 6]]


[[2 0 3]
 [1 4 5]
 [7 8 6]]


[[2 4 3]
 [1 0 5]
 [7 8 6]]


[[2 4 3]
 [1 5 0]
 [7 8 6]]


[[2 4 0]
 [1 5 3]
 [7 8 6]]


[[2 0 4]
 [1 5 3]
 [7 8 6]]


[[0 2 4]
 [1 5 3]
 [7 8 6]]


[[1 2 4]
 [0 5 3]
 [7 8 6]]


[[1 2 4]
 [5 0 3]
 [7 8 6]]


[[1 2 4]
 [5 3 0]
 [7 8 6]]


[[1 2 0]
 [5 3 4]
 [7 8 6]]


[[1 0 2]
 [5 3 4]
 [7 8 6]]


[[1 3 2]
 [5 0 4]
 [7 8 6]]


[[1 3 2]
 [5 4 0]
 [7 8 6]]


[[1 3 2]
 [5 4 6]
 [7 8 0]]


[[1 3 2]
 [5 4 6]
 [7 0 8]]


[[1 3 2]
 [5 0 6]
 [7 4 8]]


[[1 0 2]
 [5 3 6]
 [7 4 8]]


[[1 2 0]
 [5 3 6]
 [7 4 8]]


[[1 2 6]
 [5 3 0]
 [7 4 8]]


[[1 2 6]
 [5 0 3]
 [7 4 8]]


[[1 2 6]
 [5 4 3]
 [7 0 8]]


[[1 2 6]
 [5 4 3]
 [7 8 0]]


[[1 2 6]
 [5 4 0]
 [7 8 3]]


[[1 2 6]
 [5 0 4]
 [7 8 3]]


[[1 2 6]
 [0 5 4]
 [7 8 3]]


[[1 2 6]
 [7 5 4]
 [0 8 3]]


[[1 2 6]
 [7 5 4]
 [8 0 3]]


[[1 2 6]
 [7 5 4]
 [8 3 0]]


[[1 2 6]
 

## Discusta sobre o desempenho do método em questões de:


1.   Consumo de memória
2.   Processamento



**Memoria**: Não possui um custo tão alto, mas é nescessario guardar os estados(ou nós se for o caso) visitados, é mantida uma lista "aberta" com estados que devem ser expandidos, e a lista "fechada" dos que já foram expandidos.


**Processamento** : É um algoritimo bem eficiente, teve um desempenho melhor que dfs e bfs em geral, mas ainda pode ter que expandir varios nós para encontrar a solução que requer muitos movimentos, dependendo da heuristica, corre-se o risco do algoritimo se distanciar da solução.
